### ISSUE TITLE
Configure a custom domain for API GW

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#114]
Contact me with details about the custom domain.

**Comment by toddysm** [comment]
let's configure api.holodium.com

**Comment by KristinJJ** [comment]
# User Story
As a user, I want to go to a custom domain that is easier to remember than API Gateway's url

# Time to complete
Estimated: 8 hours
Actual: 15 hours

# Acceptance Criteria
- [x] The API Gateway will be accessible via custom domain https://api.holodium.com/v1/feedback

# Testing
## Testing in cURL
- [ ] Open a terminal window.
- [ ] Run ` curl -X POST https://api.holodium.com/v1/feedback -d '{"feedback":"Hello World?"}'`
- [ ] View the response JSON.

![Screen Shot 2022-03-15 at 7 19 15 PM](https://user-images.githubusercontent.com/26866132/158503753-328c77a8-0570-4e7a-8561-30ee917ccfc1.png)


## Testing in Postman
- [ ] Open [Postman](https://www.postman.com/)
- [ ] Open a new request and select POST from the drop down menu.
- [ ] Enter `https://api.holodium.com/v1/feedback` as the request URL.
- [ ] Select JSON from the drop down menu.
- [ ] Open the Body tab and enter `{
  "feedback": "YOUR_SENTENCES_HERE"
}`
- [ ] Hit the Send button to view the response JSON.

<img width="1547" alt="Screen Shot 2022-03-15 at 7 17 56 PM" src="https://user-images.githubusercontent.com/26866132/158503716-e15ff03a-8e5a-4ac7-9d68-3a7c8c0a9c23.png">


# Known Issues
- If you don't include the `https://` at the beginning of the URL, it won't work since it is configured with an SSL certificate.
- The body response code may have been updated after the writing of this documentation. As long as there is a response without an error returned from the POST method, that is considered a successful response. 

# Activities Documentation

| Date  | Activity | Time Spent |
| ------------- | ------------- | ------------- |
| 03/05/2022 | Research create a custom domain using AWS | 1 hr |
| 03/06/2022 | Research create a custom domain on AWS using Route 53 | 1 hr  |
| 03/07/2022 | Attempting to create Hosted Zone on Route 53, ran into permissions issues | 1 hr  |
| 03/10/2022 | Researching certbot | 1 hr  |
| 03/13/2022 | Installed certbot and deployed a certificate request for api.holodium.com, sent instructions to Toddy to deploy a DNS TXT record | 1 hr  |
| 03/14/2022 | Received verification from Toddy that DNS TXT record was added, found certificate, imported to AWS Certificate Manager | 1.25 hr  |
| 03/15/2022 | Created Custom Domain Name for API Gateway, added API Mapping for `v1/feedback` path, testing in Postman, researching how to add CNAME and A records to GoDaddy DNS, sent request to Toddy to add record with specific properties | 3.5 hr  |
| 03/15/2022 | Received verification from Toddy that CNAME record was added, determined that A record was not needed as it is already taken care of by AWS, testing in Postman and ran into `Missing Authentication Token` error, researching and troubleshooting error | 3 hr  |
| 03/15/2022 | More researching and troubleshooting, added POST method to v1 and was able to get around `Missing Authentication Token` | 2 hr  |
| 03/15/2022 | Update documentation | 0.25 hr  |


# Pull Request
Toddy said in class 3/15 that no PR was needed for this issue since there weren't any code changes.
