### ISSUE TITLE
SageMaker ML model for determining the sentiment of a sentences

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#119]

**Comment by eyerusalemdani** [comment]
Time taken and activities

I was trying to use the NLTK library to deploy the model in SageMaker. 2 hours
I tried using this service: https://aws.amazon.com/marketplace/pp/prodview-mc7fhbqx7ngy6 to deploy sentiment analysis, but there was additional pricing and subscription required 

I was not able to configure how to communicate with demo lambda

**Comment by eyerusalemdani** [comment]
Issue has been resolved and a pull request has been raised

# Time Taken:
1. Created new lambda function "se_85400": 30 minutes
2. Implemented logic in lambda function, but code wasn't working due to nltk library not installed by default in AWS Lambda: 3 hours
3. Uploaded zip file with the dependent folders: 2 hours
4. Configured input and output to match expected format: 1 hour

# Issues faced during development
Since the Lambda function did not have the NLTK library set up by default, I had to research how to download the library as a zip, test my function locally, and then upload the code as a zip file to AWS Lambda.
This was an interesting learning for me.
