### ISSUE TITLE
Create Lamdba function for the demo and deploy the latest code on it

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#144]
The name of the Lambda function for the demo should be `demoTuesdayLambda`.

Make sure the code includes the calls to the SageMaker APIs - this is the Lambda from #143

**Comment by aaronallenCS** [comment]
Closes #144 

Was able to create the lambda, named demoTuesdayLambda, that would've been used to make the call to the sagemaker API. Due to the sagemaker endpoints not being totally finished, I was not able to call the sage maker API. Screenshotted below is the lambda function: 


![Screenshot (116)](https://user-images.githubusercontent.com/15794743/159822510-57d6cb41-ea6d-45c3-a1d1-02fa19f381d8.png)
