### ISSUE TITLE
Configure the API gateway to point to the demo Lambda

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#145]
The instance we should configure is: `simplePostLambda-API (ID: nq7se7ngt6) to point to `demoTuesdayLambda`.

The above API gateway instance is configured for using a custom domain and SSL for `api.holodium.com/v1/feedback`

**Comment by Jflands23** [comment]
# User Story
As a developer, I want to configure my  `simplePostLambda-API` (ID: nq7se7ngt6) to point the `demoTuesdayLambda` so that when the front end team calls the url `api.holodium.com/v1/feedback` the lambda function is executed successfully

# Testing
## Testing in AWS console
- [ ] Navigate to the AWS console and search for the API gateway service
- [ ] Look for the API gateway that has the ID: nq7se7ngt6 and click on it
- [ ] navigate to the resources tab and go to the post method in the /feedback path and click Test on the left hand side right above the lighning bolt (image 1)
- [ ] In the Request body type: {"feedback": "You wrote about racing. You could have done better here.  Overall good job."}
- [ ] Click test, verify a successful response (image 2)

## Testing in Postman
- [ ] Navigate and log in to postman
- [ ] Execute a post message using the url: https://api.holodium.com/v1/feedback 
- [ ]  Select body type raw and type in  {"feedback": "You wrote about racing. You could have done better here.  Overall good job."}. Hit send
- [ ]  Your Response will be the same response as the one you got in the AWS console. (image 3)

# Pictures
1. 
![image](https://user-images.githubusercontent.com/75229373/159404804-56359a70-f2c0-40d2-8157-dbdcae12d914.png)
2. 
![image](https://user-images.githubusercontent.com/75229373/159404903-fab6339e-f5a3-4aea-abd7-3bc3ad29db65.png)


# Known Issues
- If you don't include the `https://` at the beginning of the URL, it won't work since it is configured with an SSL certificate.
- The body response code may have been updated after the writing of this documentation. As long as there is a response without an error returned from the POST method, that is considered a successful response. 


# Pull Request
There were no code changes therefore no PR was needed. All configurations were made in the AWS console
