### ISSUE TITLE
Enhance the export script to have the full feedback conversations

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#54]
# User Story
As a dev, I want to retrieve full conversations, so I can train my model with better data

# Estimated Time to Complete
4 hours

# Acceptance Criteria
- [ ] Full conversations are retrieved from floop data
    - [ ] Each message should say what the user type is who sent it (i.e. teacher or student)
- [ ] The script should accept a limit argument to limit the amount of non-duplicate conversations to query

**Comment by dansjack** [comment]
For this you'll want to determine who is sending what (is a teacher sending a message to a student, or vice-versa?)

To do that, you can look at the `Participant_IDs` field in the `Conversation` doc. Each field in `Participant_IDs` looks like this: `uid: "T"` (teacher participant) or `uid: "S"` (student participant)
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30481844/152093450-d0952707-c045-4396-baed-3557c606891f.png">

For each `Conversation`, you'll want to store the teacher(s) and student uids in variables, so you can check them against the `Sender_ID` field of each `Message` doc the `Conversation` has. In the example below, we know the `Sender_ID` belongs to a teacher because we can see it matches the first key in the `Participant_IDs` field, which has a value of `"T"`
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30481844/152093798-d4913da4-259a-43ee-855b-1359b1aff0a7.png">

**Comment by dansjack** [comment]
# Activities Documentation


| Date  | Activity | Time Spent |
| ------------- | ------------- | ------------- |
| 02/15/2022 | Research argparse, boto3, firebase_admin dependencies | 1 hr  |
| 02/15/2022 | Update script to add args | 1 hr  |
| 02/15/2022 | Update script to recursively get data in batches, so more data can be retrieved | 1.5 hr  |
| 02/15/2022 | Test | 0.5 hr  |
| 02/16/2022 | Research autopep8, scrubadub | 1 hr  |
| 02/16/2022 | Format code, adding scrubber, adding env arg | 1.5 hr |
| 02/16/2022 | Documentation | 1 hr |
