### ISSUE TITLE
Create a clustering algotithm to analyse the conversations and group by number of comments

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#84]
From the data exported from Floop we need to determine how many conversations fall into different buckets based on the number of comments. We should develop a clustering algorithm that clusters the 1000 conversations into clusters based don't he number of messages in the conversation.

**Comment by dale108** [comment]
## Time estimated:
7 hours.

## Time taken:
7 hours. 

## Link to pull request
https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/pull/104

## Description 🗒️

This algorithm takes in a set of conversations between students and teachers on the Floop Platform, and groups them by the length of the threads in a conversation.

Writing the initial clustering algorithm was simple enough, so I also wrote general solution so that we can correlate any other variable that we extrapolate from a given conversation to the total number of threads in the conversation. For example, we could generate a sentiment score for each comment in a conversation, take the sum of all the sentiment scores, and use some simple k-means clustering and simple regression math to determine whether more comments in a conversation generally indicate that the conversation was positive or negative. 

## Testing 
Both the development and production data-sets are available in our `floop-dataset` S3 bucket.

To test the script, download any file from the floop-dataset repo and enter the path to that file when the script prompts you to. 

## Result
The distribution of values in the production data looks like this 
[](https://user-images.githubusercontent.com/30481844/155583088-c616c8dc-7f29-4485-8562-15ac1b44276f.png)https://user-images.githubusercontent.com/30481844/155583088-c616c8dc-7f29-4485-8562-15ac1b44276f.png

and the distribution of data points I pulled from the dev environment looks like this:
[](https://user-images.githubusercontent.com/26866132/155670152-96010a30-147c-407f-86ad-895fb5bb78c2.png)https://user-images.githubusercontent.com/26866132/155670152-96010a30-147c-407f-86ad-895fb5bb78c2.png

The script will also print a "prediction" array of zeroes, because the correlation variable that the model treats as an output for the input of conversation length is always 0 for now. 0 is just a placeholder until we decide what quality of the conversation to correlate with the length of the conversation for analysis.
